import { sql } from '@/lib/db';
import { NextResponse } from 'next/server';

export async function GET() {
  try {
    const blogs = [
    {slug: 'building-future-of-digital-india', title: 'Building Future of digital india', description: 'India\'s digital transformation story is being written not only by large conglomerates but also by visionary technology leaders...', image: '/images/blogs/buldingDigital.png', category: 'Digital Transformation', date: '2025-12-31'},
    {slug: 'digital-transformation-journey-from-2025-achievements-and-the-road-to-2026', title: 'Digital Transformation Journey from 2025 Achievements and the Road to 2026', description: 'As the calendar turns and businesses prepare for the next wave of innovation, moments like these invite reflection, gratitude, and renewed ambition...', image: '/images/blogs/digital_transformation.png', category: 'Digital Transformation', date: '2025-12-31'},
    {slug: 'top-10-free-ai-tools-for-software-developers', title: 'Top 10 Free AI Tools for Software Developers in 2025', description: 'Discover the best free AI tools that can enhance your software development workflow and boost productivity...', image: '/images/blogs/freeai-tool.png', category: 'AI & Automation', date: '2024-03-12'},
    {slug: 'top-ecommerce-niches-us', title: 'Top eCommerce Niches in the US Market (2025)', description: 'Explore the most profitable e-commerce niches in the US market and discover new opportunities for business growth...', image: '/images/blogs/top-ecommerce-niches.png', category: 'Digital Transformation', date: '2024-03-10'},
    {slug: 'mobile-app-development-bangalore-tech-startups', title: 'Scalable Mobile App Development in Bangalore for Startups', description: 'Learn how scalable mobile app development can help Bangalore startups grow and scale their business effectively...', image: '/images/blogs/banglore_startup.png', category: 'Mobile App', date: '2024-03-08'},
    {slug: 'hyderabad-startups-app-development-mtouch-labs', title: 'Why Startups in Hyderabad Choose mTouch Labs for App Development', description: 'Discover why Hyderabad startups trust mTouch Labs for their app development needs and how we help them succeed...', image: '/images/blogs/hyderbad_startup.png', category: 'Mobile App', date: '2024-03-06'},
    {slug: 'why-modern-businesses-use-saas-for-automation', title: 'Why Every Modern Business is Using SaaS to Automate - And How You Can Too!', description: 'Learn how modern businesses are leveraging SaaS solutions to automate their operations and streamline workflows...', image: '/images/blogs/sass.png', category: 'Digital Transformation', date: '2024-03-04'},
    {slug: 'genai-rag-ai-agents-ai-powered-solutions-mtouch-labs', title: 'GenAI, RAG, AI Agents & AI-Powered Solutions by mTouch Labs', description: 'Explore how GenAI, RAG, and AI agents are transforming businesses with intelligent automation solutions...', image: '/images/blogs/GMO POSTS.png', category: 'AI & Automation', date: '2024-03-02'},
    {slug: 'frontend-mastery-tips-tools-frameworks-30-days', title: 'Frontend Mastery: Tips, Tools, and Frameworks to Level Up in 30 Days', description: 'Master frontend development with essential tips, tools, and frameworks to accelerate your learning in just 30 days...', image: '/images/blogs/frontend.png', category: 'Web Development', date: '2024-02-28'},
    {slug: 'why-businesses-fail-at-gmb-and-win-local-searches', title: 'Why 90% of Businesses Fail at GMB And How You Can Win Local Searches', description: 'Learn why most businesses fail at Google My Business optimization and discover proven strategies to win local searches...', image: '/images/blogs/why-businesses-fail-at-gmb-and-win-local-searches1.jpg', category: 'Digital Transformation', date: '2024-02-26'},
    {slug: 'voice-based-cab-booking-with-agentic-ai-no-app-needed', title: 'mTouch Labs Launches Voice-Activated Cab Booking System Powered by Agentic AI - No App or Internet Needed', description: 'Revolutionary voice-activated cab booking system powered by Agentic AI that works without apps or internet connection...', image: '/images/blogs/voice-based-cab-booking-with-agentic-ai-no-app-needed.jpg', category: 'AI & Automation', date: '2024-02-24'},
    {slug: 'mtouch-labs-digital-solutions-for-modern-businesses', title: 'mTouch Labs Services Building Smarter Digital Solutions for Modern Businesses', description: 'Discover how mTouch Labs is building smarter digital solutions to help modern businesses transform and thrive...', image: '/images/blogs/Building Smarter Digital Solutions for Modern Businesses.jpg', category: 'Digital Transformation', date: '2024-02-22'},
    {slug: 'exploring-cybersecurity-best-practices-for-cross-platform-apps', title: 'Exploring Cyber Security Best Practices for Cross-Platform Apps', description: 'Explore essential cybersecurity best practices to protect your cross-platform applications from threats and vulnerabilities...', image: '/images/blogs/cyber.jpg', category: 'Digital Transformation', date: '2024-02-20'},
    {slug: 'swiftui-is-shaping-the-future-of-ios-app-development', title: 'How SwiftUI is Shaping the Future of iOS App Development', description: 'Discover how SwiftUI is revolutionizing iOS app development with its declarative syntax and modern approach...', image: '/images/blogs/swiftui.jpg', category: 'Mobile App', date: '2024-02-18'},
    {slug: 'why-ai-edge-computing-transforming-mobile-apps', title: 'Why AI and Edge Computing Are Transforming Mobile Apps', description: 'Understand how AI and edge computing are revolutionizing mobile app development and user experiences...', image: '/images/blogs/whyai.jpg', category: 'AI & Automation', date: '2024-02-16'},
    {slug: 'web-development-is-pioneering-the-future-of-the-metaverse', title: 'How Web Development is Pioneering the Future of the Metaverse', description: 'Explore how web development technologies are shaping the future of the metaverse and immersive experiences...', image: '/images/blogs/metaverse.png', category: 'Web Development', date: '2024-02-14'},
    {slug: 'unlocking-future-it-infrastructure-aws-microservices', title: 'Unlocking the Future of IT Infrastructure with AWS Microservices', description: 'Learn how AWS microservices architecture is revolutionizing IT infrastructure and enabling scalable solutions...', image: '/images/blogs/awsmicroservices.png', category: 'Cloud & DevOps', date: '2024-02-12'},
    {slug: 'impact-of-ai-on-mobile-app-development-by-2025', title: 'The Impact of Artificial Intelligence on Mobile App Development by 2025', description: 'Discover how artificial intelligence is transforming mobile app development and what to expect by 2025...', image: '/images/blogs/impact-of-ai-on-mobile-app-development-by-2025.png', category: 'AI & Automation', date: '2024-02-10'},
    {slug: 'php-web-development-is-transforming-businesses-2025', title: 'How a PHP Web Development Company is Transforming Businesses in 2025', description: 'Learn how PHP web development companies are helping businesses transform and achieve digital success in 2025...', image: '/images/blogs/php-web-development.png', category: 'Web Development', date: '2024-02-08'},
    {slug: 'ai-automation-seo-strategies-2025', title: 'The Impact of Automation and AI on SEO Strategies in 2025', description: 'Explore how automation and AI are revolutionizing SEO strategies and reshaping digital marketing in 2025...', image: '/images/blogs/The Impact of Automation and AI on SEO Strategies in 2025.png', category: 'Digital Transformation', date: '2024-02-06'},
    {slug: 'navigating-future-custom-software-development-2025', title: 'Navigating the Future of Custom Software Development in 2025', description: 'Discover the future trends and innovations shaping custom software development in 2025 and beyond...', image: '/images/blogs/Navigating the Future of Custom Software Development in 2025.png', category: 'Digital Transformation', date: '2024-02-04'},
    {slug: 'quantum-computing-revolutionizing-software-development-ai', title: 'How Quantum Computing Will Revolutionize Software Development for AI', description: 'Explore how quantum computing is set to revolutionize software development and AI applications in unprecedented ways...', image: '/images/blogs/Quantum Computing Will Revolutionize Software Development for AI.png', category: 'AI & Automation', date: '2024-02-02'},
    {slug: 'benefits-of-ecommerce-mobile-apps', title: 'Benefits of e-commerce mobile apps', description: 'Discover the key benefits of developing e-commerce mobile apps for your business and how they can boost sales and engagement...', image: '/images/blogs/ECommerce App Development.png', category: 'Digital Transformation', date: '2024-01-30'},
    {slug: 'role-of-ai-in-ecommerce-development', title: 'The Role of AI in eCommerce Development: Transforming Online Shopping', description: 'Learn how AI is transforming eCommerce development and revolutionizing the online shopping experience for customers...', image: '/images/blogs/ai-ecommerce-development.png', category: 'AI & Automation', date: '2024-01-28'},
    {slug: 'top-generative-ai-tools-for-developers', title: 'Best Generative AI Tools and Platforms', description: 'Explore the best generative AI tools and platforms that developers are using to enhance productivity and creativity...', image: '/images/blogs/Generative AI Tools and Platforms1.png', category: 'AI & Automation', date: '2024-01-26'},
    {slug: 'ai-role-in-business-automation', title: 'AI for Business Automation - mTouch Labs', description: 'Discover how AI can transform your business operations with intelligent automation solutions from mTouch Labs...', image: '/images/blogs/ai-in-business.png', category: 'AI & Automation', date: '2024-01-24'},
    {slug: 'artificial-intelligence-transforming-mobile-technology', title: 'How Artificial Intelligence is Transforming Mobile Technology in 2024', description: 'Discover how artificial intelligence is revolutionizing mobile technology and transforming user experiences in 2024...', image: '/images/blogs/artificial-intelligence-transforming-mobile-technology.png', category: 'AI & Automation', date: '2024-01-22'},
    {slug: 'complete-guide-on-outsourcing-mobile-app-development-in-2022', title: 'Complete Guide On Outsourcing Mobile App Development In 2022', description: 'A comprehensive guide to outsourcing mobile app development, covering best practices, benefits, and key considerations...', image: '/images/blogs/guide-on-outsourcing-mobile-app-development-in-2022-blog.jpg', category: 'Mobile App', date: '2023-12-20'},
    {slug: 'ways-to-reduce-mobile-app-development-cost', title: 'Ways To Reduce Mobile App Development Cost?', description: 'Learn effective strategies and techniques to reduce mobile app development costs without compromising quality...', image: '/images/blogs/Ways To Reduce Mobile App Development Cost_ copy.jpg', category: 'Mobile App', date: '2023-12-18'},
    {slug: 'best-practices-for-mobile-app-design-trends-in-2022', title: 'Best Practices For Mobile App Design Trends In 2022', description: 'Explore the best practices and latest trends in mobile app design for 2022 and learn how to create engaging user experiences...', image: '/images/blogs/Best Practices For Mobile App Design Trends In 2022.png', category: 'Digital Transformation', date: '2023-12-16'},
    {slug: 'security-tips-for-mobile-app-developers', title: 'Security Tips For Mobile App Developers', description: 'Essential security tips and best practices for mobile app developers to protect user data and prevent vulnerabilities...', image: '/images/blogs/security-tips-for-mobile-app-developers.png', category: 'Digital Transformation', date: '2023-12-14'},
    {slug: 'top-on-demand-mobile-app-development-ideas-for-startups', title: 'Top On-Demand Mobile App Development Ideas For Startups', description: 'Explore the top on-demand mobile app development ideas that can help startups launch successful products and scale their business...', image: '/images/blogs/Top On-demand Mobile App Development Ideas For Startups.jpg', category: 'Mobile App', date: '2023-12-12'},
    {slug: '5-ways-to-convert-your-website-into-a-mobile-app', title: '5 Ways To Convert Your Website Into A Mobile App', description: 'Learn five effective methods to transform your website into a fully functional mobile app and expand your digital presence...', image: '/images/blogs/5 Ways To Convert Your Website Into A Mobile App copy.jpg', category: 'Mobile App', date: '2023-12-10'},
    {slug: 'guide-to-create-an-on-demand-mobile-app-development', title: 'Guide To Create An On-Demand Mobile App Development', description: 'Complete guide to building on-demand mobile applications that connect service providers with customers efficiently...', image: '/images/blogs/Guide To Create An On-Demand Mobile App Development copy.jpg', category: 'Mobile App', date: '2023-12-08'},
    {slug: 'how-5g-technology-is-influencing-the-world-of-mobile-application-development', title: 'How 5G Technology Is Influencing The World Of Mobile Application Development?', description: 'Discover how 5G technology is revolutionizing mobile app development with faster speeds and enhanced capabilities...', image: '/images/blogs/How 5G technology is influencing the world of Mobile Application Development_ copy.jpg', category: 'Mobile App', date: '2023-12-06'},
    {slug: 'what-makes-your-mobile-app-development-company-stand-out-in-the-crowd', title: 'What Makes Your Mobile App Development Company Stand Out In The Crowd?', description: 'Learn what differentiates successful mobile app development companies and how to stand out in a competitive market...', image: '/images/blogs/What Makes Your Mobile App Development Company Stand Out  In The Crowd.png', category: 'Mobile App', date: '2023-12-04'},
    {slug: 'the-ultimate-guide-to-create-an-ecommerce-mobile-app-development', title: 'The Ultimate Guide To Create An ECommerce Mobile App Development', description: 'Comprehensive guide to creating successful eCommerce mobile applications that drive sales and customer engagement...', image: '/images/blogs/The Ultimate Guide To Create An ECommerce Mobile App Development copy.jpg', category: 'Digital Transformation', date: '2023-12-02'},
    {slug: 'does-my-business-need-a-mobile-app', title: 'Does My Business Need A Mobile App?', description: 'Explore whether your business needs a mobile app and understand the benefits it can bring to your operations...', image: '/images/blogs/Does My Business Need A Mobile App_ copy.jpg', category: 'Mobile App', date: '2023-11-30'},
    {slug: 'is-your-mobile-app-development-company-prepared-for-the-5g-revolution', title: 'Is Your Mobile App Development Company Prepared For The 5G Revolution?', description: 'Understand how to prepare your mobile app development company for the upcoming 5G revolution and its impact...', image: '/images/blogs/Factors That Affect The Success Of Mobile App Development-1 copy.jpg', category: 'Mobile App', date: '2023-11-28'},
    {slug: 'key-advantages-of-cross-platform-mobile-app-development', title: 'Key Advantages Of Cross-Platform Mobile App Development', description: 'Discover the key benefits of cross-platform mobile app development for cost-effective and efficient solutions...', image: '/images/blogs/Key Advantages of Cross-Platform Mobile App Development copy.png', category: 'Mobile App', date: '2023-11-26'},
    {slug: 'how-to-perform-a-successful-business-plan-for-your-mobile-app-development', title: 'How To Perform A Successful Business Plan For Your Mobile App Development?', description: 'Learn how to create a comprehensive business plan for successful mobile app development projects...', image: '/images/blogs/Mobile App Development Business Plan copy.png', category: 'Mobile App', date: '2023-11-24'},
    {slug: 'top-mobile-app-development-companies-in-hyderabad', title: 'mTouch Labs Is Regarded As One Of The Top Mobile App Development Companies In Hyderabad.', description: 'Discover why mTouch Labs is recognized as one of the leading mobile app development companies in Hyderabad...', image: '/images/blogs/mTouch-Labs-Regarded-As-Top-Mobile-App-Development-Companies-In-Hyderabad.jpg', category: 'Mobile App', date: '2023-11-22'},
    {slug: 'a-complete-guide-to-cloud-security-in-2023', title: 'A Complete Guide to Cloud Security in 2023', description: 'Comprehensive guide to cloud security best practices and strategies to protect your cloud infrastructure...', image: '/images/blogs/a-complete-guide-to-cloud-security-in-2023.png', category: 'Cloud & DevOps', date: '2023-11-20'},
    {slug: 'android-app-development-company-in-india', title: 'Android App Development Company in India', description: 'Learn about professional Android app development services in India and how to choose the right partner...', image: '/images/blogs/android-app-development-company-in-india.jpg', category: 'Mobile App', date: '2023-11-18'},
    {slug: 'navigating-the-world-of-mobile-application-apps', title: 'Navigating the World of Mobile Application Apps', description: 'Explore the diverse landscape of mobile applications and learn how to navigate the app development ecosystem...', image: '/images/blogs/navigating-the-world-of-mobile-application-apps.jpg', category: 'Mobile App', date: '2023-11-16'},
    {slug: 'milk-delivery-app-development-company', title: 'Milk Delivery App Development Company', description: 'Discover how to build efficient milk delivery applications that streamline operations and improve customer service...', image: '/images/blogs/milk-delivery-app-development-company.png', category: 'Mobile App', date: '2023-11-14'},
    {slug: 'iso-certified-mobile-app-development-company', title: 'ISO-Certified Mobile App Development Company', description: 'Learn about the importance of ISO certification in mobile app development and quality assurance standards...', image: '/images/blogs/iso-certified-mobile-app-development-company.jpg', category: 'Mobile App', date: '2023-11-12'},
    {slug: 'how-artificial-intelligence-is-transforming-mobile-app-development', title: 'How Artificial Intelligence Is Transforming Mobile App Development?', description: 'Discover how AI is revolutionizing mobile app development with intelligent features and automation capabilities...', image: '/images/blogs/How Artificial Intelligence Is Transforming Mobile App Development_ copy.jpg', category: 'AI & Automation', date: '2023-11-10'},
    {slug: 'ios-mobile-app-development-vs-android-mobile-app-development', title: 'iOS Mobile App Development Vs Android Mobile App Development', description: 'Compare iOS and Android mobile app development platforms to choose the best option for your project...', image: '/images/blogs/ios-mobile-app-development-vs-android-mobile-app-development-blog.jpg', category: 'Mobile App', date: '2023-11-08'},
    {slug: 'choosing-the-best-mobile-app-development-company', title: 'Choosing The Best Mobile App Development Company', description: 'Essential tips and criteria for selecting the right mobile app development company for your business needs...', image: '/images/blogs/Choosing The Best Mobile App Development Company copy.jpg', category: 'Mobile App', date: '2023-11-06'},
    {slug: 'why-every-business-should-invest-in-a-mobile-app-development', title: 'Why Every Business Should Invest In A Mobile App Development?', description: 'Understand the compelling reasons why every modern business should invest in mobile app development...', image: '/images/blogs/Why Every Business Should Invest In A Mobile App Development copy.png', category: 'Mobile App', date: '2023-11-04'},
    {slug: 'top-mobile-app-development-trends-in-2021', title: 'Top Mobile App Development Trends In 2021', description: 'Explore the latest mobile app development trends that are shaping the industry and driving innovation...', image: '/images/blogs/top-mobile-app-development-trends-in-2021-blog.jpg', category: 'Mobile App', date: '2023-11-02'},
    {slug: 'factors-that-affect-the-success-of-mobile-app-development', title: 'Factors That Affect The Success Of Mobile App Development', description: 'Identify the key factors that determine the success of mobile app development projects and outcomes...', image: '/images/blogs/factors-that-affect-the-success-of-mobile-app-development-blog.jpg', category: 'Mobile App', date: '2023-10-30'},
    {slug: 'guide-to-create-an-ecommerce-mobile-application-development', title: 'Guide To Create An ECommerce Mobile Application Development', description: 'Step-by-step guide to developing successful eCommerce mobile applications for your online business...', image: '/images/blogs/Guide to Create an ECommerce Mobile Application Developmen copy.jpg', category: 'Digital Transformation', date: '2023-10-28'},
    {slug: 'redefining-the-app-development-business-amid-pandemic-situation', title: 'Redefining The App Development Business Amid Pandemic Situation', description: 'Learn how the app development industry adapted and evolved during the pandemic to meet new challenges...', image: '/images/blogs/Redefining-The-App-Development-Business-Amid-Pandemic-Situation.jpg', category: 'Mobile App', date: '2023-10-26'},
    {slug: 'mtouch-labs-sets-a-platform-for-indian-short-video-sharing-app', title: 'mTouch Labs Sets A Platform For Indian Short Video Sharing App', description: 'Discover how mTouch Labs created an innovative platform for Indian short video sharing applications...', image: '/images/blogs/MTouch Labs Sets A Platform For Indian Short Video Sharing App copy.jpg', category: 'Mobile App', date: '2023-10-24'},
    {slug: 'mobile-app-development-guide-the-definitive-guide-for-2020', title: 'MOBILE APP DEVELOPMENT GUIDE- The Definitive Guide For 2020', description: 'The complete guide to mobile app development covering all essential aspects and best practices...', image: '/images/blogs/MOBILE APP DEVELOPMENT GUIDE- The Definitive Guide For 2020 copy.jpg', category: 'Mobile App', date: '2023-10-22'},
    {slug: 'types-of-mobile-app-development-services-for-your-business', title: 'Types Of Mobile App Development Services For Your Business', description: 'Explore different types of mobile app development services available to meet your business requirements...', image: '/images/blogs/impacts-of-apple\'s-ios-14-app-clips-on-features-&-tools.jpg', category: 'Mobile App', date: '2023-10-20'},
    {slug: 'impacts-of-apples-ios-14-app-clips-on-features-and-tools', title: 'Impacts Of Apple\'s iOS 14 App Clips On Features & Tools', description: 'Understand how Apple\'s iOS 14 App Clips feature impacts app development and user experience...', image: '/images/blogs/Types Of Mobile App Development Services For Your Business copy.jpg', category: 'Mobile App', date: '2023-10-18'},
    {slug: 'on-demand-mobile-app-development-solutions-for-your-business-needs', title: 'On-Demand Mobile App Development Solutions For Your Business Needs', description: 'Discover on-demand mobile app development solutions tailored to your specific business requirements...', image: '/images/blogs/On-Demand Mobile App Development Solutions For Your Business Needs copy.jpg', category: 'Mobile App', date: '2023-10-16'},
    {slug: 'mobile-applications-to-enhance-your-business-growth', title: 'Mobile Applications To Enhance Your Business Growth', description: 'Learn how mobile applications can significantly enhance your business growth and customer engagement...', image: '/images/blogs/mobile-applications-to-enhance-your-business-growth-blog.jpg', category: 'Mobile App', date: '2023-10-14'},
    {slug: 'developing-innovative-mobile-apps-using-cutting-edge-technologies', title: 'Developing Innovative Mobile Apps Using Cutting Edge Technologies', description: 'Explore how to develop innovative mobile apps using the latest cutting-edge technologies and frameworks...', image: '/images/blogs/Developing Innovative Mobile Apps Using Cutting Edge Technologies copy.jpg', category: 'Mobile App', date: '2023-10-12'},
    {slug: 'delivering-a-customer-centric-range-mobile-applications', title: 'Delivering A Customer-Centric Range Mobile Applications', description: 'Learn how to deliver customer-centric mobile applications that meet user expectations and drive engagement...', image: '/images/blogs/DELIVERING A CUSTOMER-CENTRIC RANGE MOBILE APPLICATIONS copy.jpg', category: 'Mobile App', date: '2023-10-10'},
    {slug: 'best-tech-stack-for-mobile-app-development', title: 'Best Tech Stack For Mobile App Development', description: 'Discover the best technology stacks for mobile app development to build robust and scalable applications...', image: '/images/blogs/Best Tech Stack For Mobile App Development copy.jpg', category: 'Mobile App', date: '2023-10-08'},
    {slug: 'ios-app-development-vs-android-app-development', title: 'iOS App Development Vs Android App Development', description: 'Compare iOS and Android app development platforms to determine the best choice for your mobile project...', image: '/images/blogs/ios-app-development-vs-android-app-development-blog.jpg', category: 'Mobile App', date: '2023-10-06'},
    {slug: 'do-we-really-need-mobile-app-development-for-everything', title: 'Do We Really Need Mobile App Development For Everything?', description: 'Explore when mobile app development is necessary and when alternative solutions might be more appropriate...', image: '/images/blogs/do-we-need-mobile-app 1 copy.jpg', category: 'Mobile App', date: '2023-10-04'},
    {slug: 'go-crazy-with-smart-phone-mobile-application-development', title: 'Go Crazy With Smart Phone Mobile Application Development', description: 'Unleash creativity in smartphone mobile application development with innovative features and designs...', image: '/images/blogs/Go Crazy With Smart Phone Mobile Application Development copy.jpg', category: 'Mobile App', date: '2023-10-02'},
    {slug: 'hmtv-interview-mtouch-labs', title: 'HMTV Interview MTouch Labs', description: 'Watch the HMTV interview featuring mTouch Labs discussing innovation and technology trends...', image: '/images/blogs/HMTV-Interview-MTouch-Labs.jpg', category: 'Digital Transformation', date: '2023-09-30'},
    {slug: 'dubshoot-app-got-featured-in-eenadu-news-paper', title: 'Dubshoot App Got Featured In EEnadu News Paper', description: 'Read about how the Dubshoot app made headlines by getting featured in EEnadu newspaper...', image: '/images/blogs/Dubshoot App Got Featured In EEnadu News Paper copy.jpg', category: 'Mobile App', date: '2023-09-28'},
    {slug: 'everything-you-need-to-know-about-the-latest-features-of-flutter-3', title: 'Everything You Need To Know About The Latest Features Of Flutter 3.0', description: 'Comprehensive guide to Flutter 3.0\'s latest features and improvements for cross-platform development...', image: '/images/blogs/everything-you-need-to-know-about-the-latest-features-of-flutter-3.0-blog.jpg', category: 'Mobile App', date: '2023-09-26'},
    {slug: 'best-cross-platform-app-development-frameworks-in-2022', title: 'Best Cross-Platform App Development Frameworks in 2022', description: 'Explore the top cross-platform app development frameworks to build efficient multi-platform applications...', image: '/images/blogs/best-cross-platform-app-development-frameworks-in-2022-blog-detail.jpg', category: 'Mobile App', date: '2023-09-24'},
    {slug: 'a-complete-guide-on-ecommerce-mobile-app-development', title: 'A Complete Guide On eCommerce Mobile App Development', description: 'Complete guide to developing successful eCommerce mobile applications that drive sales and growth...', image: '/images/blogs/a-complete-guide-on-ecommerce-app-development-blog.png', category: 'Digital Transformation', date: '2023-09-22'},
    {slug: 'top-web-development-challenges-you-should-not-miss-in-2022', title: 'Top Web Development Challenges You Shouldn\'t Miss In 2022', description: 'Discover the major web development challenges of 2022 and how to overcome them effectively...', image: '/images/blogs/top-web-development-challenges-you-should-not-miss-in-2022.jpg', category: 'Web Development', date: '2023-09-20'},
    {slug: 'tips-and-trends-to-improve-your-web-design-in-2023', title: 'Tips & Trends To Improve Your Web Design 2023', description: 'Learn the latest tips and trends to enhance your web design and create stunning user experiences...', image: '/images/blogs/tips-&-trends-to-improve-your-web-design-2023-main.jpg', category: 'Web Development', date: '2023-09-18'},
    {slug: 'openai-for-a-mobile-app-development-company', title: 'The Potential of OpenAI for a Mobile App Development Company', description: 'Explore how OpenAI is transforming mobile app development with AI-powered features and capabilities...', image: '/images/blogs/openai-for-a-mobile-app-development-company.jpg', category: 'AI & Automation', date: '2023-09-16'},
    {slug: 'best-web-development-company-in-hyderabad', title: 'Best Web Development Company in Hyderabad', description: 'Discover the best web development companies in Hyderabad for your next digital project...', image: '/images/blogs/best-web-development-company-in-hyderabad.jpg', category: 'Web Development', date: '2023-09-14'},
    {slug: 'top-hybrid-app-development-company-in-hyderabad', title: 'Top Hybrid App Development Company in Hyderabad', description: 'Find the top hybrid app development companies in Hyderabad for cross-platform solutions...', image: '/images/blogs/top-hybrid-app-development-company-in-hyderabad.jpg', category: 'Mobile App', date: '2023-09-12'},
    ];

    let inserted = 0;
    for (const blog of blogs) {
      await sql`
        INSERT INTO blogs (slug, title, description, image, author, category, meta_title, meta_description, published, created_at)
        VALUES (${blog.slug}, ${blog.title}, ${blog.description}, ${blog.image}, 'mTouch Labs', ${blog.category}, ${blog.title}, ${blog.description}, true, ${blog.date})
        ON CONFLICT (slug) DO UPDATE SET
          title = EXCLUDED.title,
          description = EXCLUDED.description,
          image = EXCLUDED.image,
          category = EXCLUDED.category,
          meta_title = EXCLUDED.meta_title,
          meta_description = EXCLUDED.meta_description
      `;
      inserted++;
    }

    return NextResponse.json({
      success: true,
      message: `Seeded ${inserted} of ${blogs.length} blog posts`,
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}