
import '../public/css/brand.css';
import "../public/css/case-study.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import ChatWidget from "@/components/layout/ChatWidget";
import Script from "next/script";
import QuoteModal from "@/components/sections/home/QuoteModal";
import Analytics from "@/components/Analytics";
import AOSRefresh from "@/components/AOSRefresh";
import ScrollRestorationManager from "@/components/ScrollRestorationManager";
import type { Viewport } from "next";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#3E8CFB",
};

export const metadata = {
  metadataBase: new URL('https://www.mtouchlabs.com'),
  // NOTE: no global `alternates.canonical` here — a root-layout canonical
  // cascades to every page that doesn't override it, telling Google those
  // pages are duplicates of the homepage. Each page sets its own canonical.
  title: {
    default: "Software Development Company & IT Solutions | mTouch Labs",
    template: "%s | mTouch Labs"
  },
  description: "mTouch Labs is a leading software development company providing mobile app development, web development, and digital marketing services.",
  openGraph: {
    siteName: "mTouch Labs",
    type: "website",
    locale: "en_US",
    images: [
      {
        url: "/images/Light.png",
        width: 1200,
        height: 630,
        alt: "mTouch Labs Software Development Company"
      }
    ]
  },
  twitter: {
    card: "summary_large_image",
    site: "@mtouchlabs",
    creator: "@mtouchlabs",
    title: "Software Development Company & IT Solutions | mTouch Labs",
    description: "mTouch Labs is a leading software development company providing mobile app development, web development, and digital marketing services.",
    images: ["/images/Light.png"]
  },
  icons: {
    // Google Search only supports .ico/.png favicons — a /favicon.ico at the
    // server root is required. Files are generated by scripts/generate-favicons.mjs.
    icon: [
      { url: "/favicon.ico", sizes: "any" },                              // Google Search + legacy browsers
      { url: "/favicon.svg", type: "image/svg+xml" },                     // modern browsers, scales at any size
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },   // crisp browser-tab icon
      { url: "/images/icon-48.png", sizes: "48x48", type: "image/png" },
      { url: "/images/icon-96.png", sizes: "96x96", type: "image/png" },
      { url: "/images/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    shortcut: "/favicon.ico",
    apple: { url: "/images/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
  },
  manifest: "/manifest.json",
  authors: [{ name: "mTouch Labs", url: "https://www.mtouchlabs.com" }],
  creator: "mTouch Labs",
  publisher: "mTouch Labs",
  category: "Technology",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* ========== RESOURCE HINTS — open connections to render-blocking
            third-party origins early to speed up FCP/LCP. ========== */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://cdnjs.cloudflare.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://unpkg.com" />
        <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
        {/* ========== GOOGLE TAG MANAGER (GTM) — Global, all pages ========== */}
        <Script id="gtm-init" strategy="afterInteractive">
          {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-K2PX82J8');`}
        </Script>
        {/* ========== END GOOGLE TAG MANAGER ========== */}

        {/* ========== GOOGLE TAG (gtag.js) — Ads + Analytics ========== */}
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=G-XKH5MQ5FD4`}
          strategy="afterInteractive"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-17755266570');
            gtag('config', 'G-XKH5MQ5FD4');
          `}
        </Script>
        <Script src="https://challenges.cloudflare.com/turnstile/v0/api.js" strategy="lazyOnload" />

        {/* ========== SCHEMA.ORG — Organization ========== */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              "@id": "https://www.mtouchlabs.com/#organization",
              "name": "mTouch Labs",
              "url": "https://www.mtouchlabs.com",
              // Google requires the logo to be ≥112×112px — favicon.png (100×100) fails that.
              "logo": "https://www.mtouchlabs.com/images/Light.png",
              "description": "Leading software development company specializing in web and mobile app development, partnering with Telangana and Abu Dhabi Governments.",
              "foundingDate": "2014",
              "address": {
                "@type": "PostalAddress",
                "addressLocality": "Hyderabad",
                "addressRegion": "Telangana",
                "postalCode": "500072",
                "addressCountry": "IN"
              },
              "contactPoint": [
                { "@type": "ContactPoint", "telephone": "+91-9390683154", "contactType": "sales", "areaServed": "IN" },
                { "@type": "ContactPoint", "telephone": "+1-551-222-0070", "contactType": "sales", "areaServed": "US" }
              ],
              "sameAs": [
                "https://www.linkedin.com/company/mtouchlabs",
                "https://www.instagram.com/mtouchlabs",
                "https://twitter.com/mtouchlabs",
                "https://www.facebook.com/mtouchlabs",
                "https://www.youtube.com/@mtouchlabs"
              ]
            })
          }}
        />

        {/* ========== SCHEMA.ORG — WebSite ========== */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              "name": "mTouch Labs",
              "url": "https://www.mtouchlabs.com",
              "publisher": { "@id": "https://www.mtouchlabs.com/#organization" }
            })
          }}
        />

        {/* ========== CSS — BUNDLED ==========
            All 17 local stylesheets (bootstrap.min, plugin.min, all.min,
            ionicon.min, style, responsive, mega-menu, about, blog,
            home-mega-menu, navbar-redesign, chat-widget, location-pages,
            navbar-dropdown, services, homepage-fixes, ui-fixes) are
            concatenated in their original cascade order and minified into a
            single file by scripts/_css_bundle.py. This drops 16 render-blocking
            requests to 1. Re-run that script after editing any source CSS, then
            bump the ?v= cache-buster below. ========== */}
        <link href="/css/bundle.css?v=20260628b" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Lora:wght@400;500;600;700&family=Sora:wght@600;700;800&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        />

        <meta name="turnstile-site-key" content={process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY} />

        {/* ========== CSS — Third Party ========== */}
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
        />

        {/* Component CSS that used to be injected inline via
            <style dangerouslySetInnerHTML> in ~20 components (~32 KB of every
            HTML response). Extracted to a cacheable file by hand; MUST stay the
            last stylesheet so these rules keep the precedence they had as
            body-level <style> tags. Bump ?v= when editing it. */}
        <link href="/css/component-styles.css?v=1" rel="stylesheet" />

        {/* Favicon links are emitted by the `icons` field in the metadata export above */}
      </head>
      <body suppressHydrationWarning>
        {/* ========== GOOGLE TAG MANAGER (noscript) — Global, all pages ========== */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-K2PX82J8"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>
        {/* ========== END GOOGLE TAG MANAGER (noscript) ========== */}

        <Analytics />
        <AOSRefresh />
        <ScrollRestorationManager />
        {/* Request Quote Modal Overlay (shared) */}
        <QuoteModal />
        {/* Brochure Modal Overlay */}
        <div className="modal-overlay hide" id="brochureModal" role="dialog" aria-modal="true" aria-labelledby="brochureModalTitle">
          <div className="brochure-modal-box">
            <div className="brochure-modal-left">
              <div className="brochure-modal-circle">
                <img width={516} height={546} loading="lazy" decoding="async" src="/images/sliders/mobile_app_development.webp" alt="Web and Mobile App Development" />
              </div>
            </div>
            <div className="brochure-modal-right">
              <button id="closeBrochureModal" className="brochure-close-btn" aria-label="Close brochure modal" type="button">&#10005;</button>
              <h3 id="brochureModalTitle" className="brochure-modal-title">Request Brochure</h3>
              <form id="brochureForm" noValidate>
                <label className="brochure-form-label" htmlFor="brochure_name">Full Name</label>
                <div className="brochure-input-group">
                  <span className="brochure-input-icon">&#128100;</span>
                  <input type="text" id="brochure_name" name="name" placeholder="Full Name" aria-label="Full Name" autoComplete="name" required />
                </div>
                <div className="brochure-error" id="brochure_name_err" aria-live="polite"></div>

                <label className="brochure-form-label" htmlFor="brochure_email">Your Email</label>
                <div className="brochure-input-group">
                  <span className="brochure-input-icon">&#9993;&#65039;</span>
                  <input type="email" id="brochure_email" name="email" placeholder="Email Id" aria-label="Email Address" autoComplete="email" required />
                </div>
                <div className="brochure-error" id="brochure_email_err" aria-live="polite"></div>

                <label className="brochure-form-label" htmlFor="brochure_country">Country Code</label>
                <select id="brochure_country" name="countryCode" className="brochure-form-select" aria-label="Country Code">
                  <option value="+91">India (+91)</option>
                  <option value="+1">USA (+1)</option>
                  <option value="+44">UK (+44)</option>
                  <option value="+61">Australia (+61)</option>
                  <option value="+971">UAE (+971)</option>
                  <option value="+65">Singapore (+65)</option>
                  <option value="+49">Germany (+49)</option>
                  <option value="+33">France (+33)</option>
                  <option value="+81">Japan (+81)</option>
                  <option value="+86">China (+86)</option>
                  <option value="+974">Qatar (+974)</option>
                  <option value="+965">Kuwait (+965)</option>
                  <option value="+966">Saudi Arabia (+966)</option>
                  <option value="+1-ca">Canada (+1)</option>
                </select>

                <label className="brochure-form-label" htmlFor="brochure_phone">Your Mobile</label>
                <div className="brochure-input-group">
                  <span className="brochure-input-icon">&#128241;</span>
                  <input type="tel" id="brochure_phone" name="mobile" placeholder="Contact Number" aria-label="Phone Number" autoComplete="tel" inputMode="numeric" pattern="[0-9]*" maxLength={10} required />
                </div>
                <div className="brochure-error" id="brochure_phone_err" aria-live="polite"></div>

                <div className="cf-turnstile" data-sitekey={process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY} data-callback="onBrochureTurnstileSuccess" suppressHydrationWarning></div>

                <button type="submit" id="brochureSubmitBtn" className="brochure-submit-btn">Submit Now</button>
                <div className="brochure-error brochure-error--form" id="brochure_form_err" aria-live="polite"></div>
              </form>
            </div>
          </div>
        </div>
        <Header />
        <div className="header-spacer"></div>
        {children}
        <Footer />
        {process.env.NEXT_PUBLIC_SHOW_CHATBOT === "true" && <ChatWidget />}
        {/* Floating WhatsApp Button — green circle with white phone
            glyph rendered via CSS mask + two animated pulsing rings
            (see .whatsapp-hero-btn rules in public/css/ui-fixes.css). */}
        <a
          href="https://wa.me/message/H5VADFWLMPYIM1"
          target="_blank"
          rel="noopener noreferrer"
          className="whatsapp-hero-btn"
          aria-label="Chat on WhatsApp"
        >
          {/* Hidden — kept for alt-text / SEO. CSS hides this element. */}
          <img width={34} height={34} loading="lazy" decoding="async"
            src="/images/new_home/ai-product-pages/cybersecurity/whatsapp.webp"
            alt="WhatsApp"
            className="whatsapp-hero-img"
          />
          {/* Foreground white phone glyph (CSS-masked SVG). */}
          <span className="whatsapp-glyph" aria-hidden="true" />
          <span className="wa-tooltip">Chat with us!</span>
        </a>

        {/* ========== JS — Core Libraries ========== */}
        <Script src="/js/jquery-3.6.0.min.js" strategy="afterInteractive" />
        <Script src="/js/bootstrap.bundle.min.js" strategy="afterInteractive" />
        {/* <Script id="app-bundle" strategy="afterInteractive" dangerouslySetInnerHTML={{ __html: `(function c(){if(typeof jQuery!=="undefined"){var s=document.createElement("script");s.src="/js/app.bundle.js";s.onload=function(){var n=document.createElement("script");n.src="/js/navbar-init.js";document.body.appendChild(n)};document.body.appendChild(s)}else{setTimeout(c,100)}})()` }} /> */}
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" strategy="afterInteractive" />
        <Script src="https://unpkg.com/aos@2.3.1/dist/aos.js" strategy="afterInteractive" />

        {/* ========== JS — Site Scripts ========== */}
        {/* <Script id="main-js" strategy="lazyOnload" dangerouslySetInnerHTML={{ __html: `(function c(){if(typeof jQuery!=="undefined"){var s=document.createElement("script");s.src="/js/main.js";document.body.appendChild(s)}else{setTimeout(c,100)}})()` }} /> */}
        
        <Script src="/js/app.bundle.js" strategy="afterInteractive" />
        
<Script src="/js/navbar-init.js" strategy="afterInteractive" />
<Script src="/js/main.js" strategy="afterInteractive" />
        <Script src="/js/mega-menu.js" strategy="lazyOnload" />

        <Script src="/js/site-interactions.js" strategy="lazyOnload" />
        <Script src="/js/faq.js" strategy="afterInteractive" />
        <Script src="/js/tabs.js" strategy="lazyOnload" />
        <Script src="/js/services.js" strategy="lazyOnload" />

 {/* <script src="/js/nav-active.js"></script> */}

        {/* ========== JS — Request Quote Handler ========== */}
        <Script src="/js/request-quote-handler.js" strategy="afterInteractive" />

        {/* ========== JS — Brochure Form Handler (country-aware validation, modal-only) ========== */}
       <Script src="/js/brochure-form-handler.js" strategy="afterInteractive" />

        {/* ========== JS — Bottom Nav Icons ========== */}
        <Script src="/js/bottom-nav-icons.js" strategy="lazyOnload" />

        <Script src="/js/tawk-loader.js" strategy="lazyOnload" />


      </body>
    </html>
  );
}