
import '../public/css/brand.css';
import "../public/css/case-study.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import ChatWidget from "@/components/layout/ChatWidget";
import Script from "next/script";
import QuoteModal from "@/components/sections/home/QuoteModal";
import Analytics from "@/components/Analytics";
import AOSRefresh from "@/components/AOSRefresh";
import ScrollRestorationManager from "@/components/ScrollRestorationManager";
import ExternalizeInternalLinks from "@/components/ExternalizeInternalLinks";
import FaqAccordion from "@/components/FaqAccordion";
import type { Viewport } from "next";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#3E8CFB",
};

/*
 * Set this to the founder's name to complete the Organization schema.
 * Left empty deliberately — see the note beside `founder` below.
 */
const FOUNDER_NAME = "";

export const metadata = {
  metadataBase: new URL('https://www.mtouchlabs.com'),
  // NOTE: no global `alternates.canonical` here — a root-layout canonical
  // cascades to every page that doesn't override it, telling Google those
  // pages are duplicates of the homepage. Each page sets its own canonical.
  title: {
    default: "Software Development Company & IT Solutions | mTouch Labs",
    template: "%s | mTouch Labs"
  },
  description: "mTouch Labs is a leading software development company providing mobile app development, web development, and digital marketing services.",
  openGraph: {
    siteName: "mTouch Labs",
    type: "website",
    locale: "en_US",
    images: [
      {
        url: "/images/Light.png",
        width: 1200,
        height: 630,
        alt: "mTouch Labs Software Development Company"
      }
    ]
  },
  twitter: {
    card: "summary_large_image",
    site: "@mtouchlabs",
    creator: "@mtouchlabs",
    title: "Software Development Company & IT Solutions | mTouch Labs",
    description: "mTouch Labs is a leading software development company providing mobile app development, web development, and digital marketing services.",
    images: ["/images/Light.png"]
  },
  icons: {
    // Google Search only supports .ico/.png favicons — a /favicon.ico at the
    // server root is required. Files are generated by scripts/generate-favicons.mjs.
    icon: [
      { url: "/favicon.ico", sizes: "any" },                              // Google Search + legacy browsers
      { url: "/favicon.svg", type: "image/svg+xml" },                     // modern browsers, scales at any size
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },   // crisp browser-tab icon
      { url: "/images/icon-48.png", sizes: "48x48", type: "image/png" },
      { url: "/images/icon-96.png", sizes: "96x96", type: "image/png" },
      { url: "/images/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    shortcut: "/favicon.ico",
    apple: { url: "/images/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
  },
  manifest: "/manifest.json",
  authors: [{ name: "mTouch Labs", url: "https://www.mtouchlabs.com" }],
  creator: "mTouch Labs",
  publisher: "mTouch Labs",
  category: "Technology",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* ========== RESOURCE HINTS — open connections to render-blocking
            third-party origins early to speed up FCP/LCP. ========== */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://cdnjs.cloudflare.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://unpkg.com" />
        <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
        {/* ========== GOOGLE TAG MANAGER (GTM) — Global, all pages ========== */}
        <Script id="gtm-init" strategy="afterInteractive">
          {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-K2PX82J8');`}
        </Script>
        {/* ========== END GOOGLE TAG MANAGER ========== */}

        {/* ========== GOOGLE TAG (gtag.js) — Ads + Analytics ========== */}
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=G-XKH5MQ5FD4`}
          strategy="afterInteractive"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-17755266570');
            gtag('config', 'G-XKH5MQ5FD4');
          `}
        </Script>
        <Script src="https://challenges.cloudflare.com/turnstile/v0/api.js" strategy="lazyOnload" />

        {/* ========== SCHEMA.ORG — Organization ========== */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              "@id": "https://www.mtouchlabs.com/#organization",
              "name": "mTouch Labs",
              "url": "https://www.mtouchlabs.com",
              // Google requires the logo to be ≥112×112px — favicon.png (100×100) fails that.
              "logo": "https://www.mtouchlabs.com/images/Light.png",
              /* Word-for-word the WHO_WE_ARE paragraph rendered on the
                 homepage and published in public/.well-known/llms.txt.
                 All three have to say the same thing: a figure that
                 disagrees with itself across a site gets discounted. */
              "description": "mTouch Labs Private Limited (trading as mTouch Labs) is a software development company incorporated on 30 August 2012 and headquartered in Hyderabad, Telangana, India, with additional offices in Bengaluru, India and Dover, Delaware, USA. It builds custom software, enterprise applications, AI-powered products, mobile apps, web platforms and SaaS products, and has delivered 1,500+ projects for 500+ clients across 12+ countries in 14+ years of operation. mTouch Labs is ISO 9001 and ISO 27001 certified and a NASSCOM member, has delivered platforms for the Government of Telangana and the Government of Abu Dhabi, and won the Digital Transformation Catalyst award at the NASSCOM SME Inspire Awards 2026.",
              "legalName": "mTouch Labs Private Limited",
              /* 2012, not 2014. The old value contradicted the "14+ years"
                 claimed everywhere in the copy — 2014 would make it 12. */
              "foundingDate": "2012-08-30",
              "address": {
                "@type": "PostalAddress",
                /* streetAddress was missing entirely. Google will not show
                   a local knowledge panel without it. Value as published
                   on /contact-us. */
                "streetAddress": "#514, Manjeera Trinity Corporate, JNTU\u2013Hitech City Road, Kukatpally",
                "addressLocality": "Hyderabad",
                "addressRegion": "Telangana",
                "postalCode": "500072",
                "addressCountry": "IN"
              },
              /* The award, named with its category and year. */
              "award": [
                "Digital Transformation Catalyst, NASSCOM SME Inspire Awards 2026"
              ],
              "hasCredential": ["ISO 9001", "ISO 27001"],
              "memberOf": {
                "@type": "Organization",
                "name": "NASSCOM",
                "alternateName": "National Association of Software and Service Companies",
                "url": "https://nasscom.in/"
              },
              /* FOUNDER — the one field this could not be filled in for.
                 No leadership page on the site names a person: /leadership-team
                 lists roles only ("Founder & CEO", "Chief Technology Officer")
                 with no names attached, so there was nothing to source and
                 nothing was invented.

                 TO COMPLETE: put the founder's name in FOUNDER_NAME at the
                 top of this file. While it is an empty string the field is
                 omitted from the JSON entirely, which is valid — a founder
                 node with a placeholder name would not be. Adding the same
                 names to /leadership-team is what makes this corroborated
                 rather than merely asserted. */
              ...(FOUNDER_NAME
                ? { "founder": { "@type": "Person", "name": FOUNDER_NAME, "jobTitle": "Founder & CEO" } }
                : {}),
              "contactPoint": [
                { "@type": "ContactPoint", "telephone": "+91-9390683154", "contactType": "sales", "areaServed": "IN" },
                { "@type": "ContactPoint", "telephone": "+1-551-222-0070", "contactType": "sales", "areaServed": "US" }
              ],
              "sameAs": [
                "https://www.linkedin.com/company/mtouchlabs",
                "https://www.instagram.com/mtouchlabs",
                "https://twitter.com/mtouchlabs",
                "https://www.facebook.com/mtouchlabs",
                "https://www.youtube.com/@mtouchlabs"
              ]
            })
          }}
        />

        {/* ========== SCHEMA.ORG — WebSite ========== */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              "name": "mTouch Labs",
              "url": "https://www.mtouchlabs.com",
              "publisher": { "@id": "https://www.mtouchlabs.com/#organization" }
            })
          }}
        />

        {/* ========== OPENAI PIXEL — Global, all pages ==========
            Setup code from OpenAI Ads Manager, pasted verbatim and present
            exactly once. Lives in <head> as requested. The snippet installs
            the `oaiq` queue stub synchronously and loads oaiq.min.js async,
            so it does not block rendering.
            The Lead conversion is sent from /thank-you — see
            lib/openaiLead.ts. Do not add a second copy anywhere. ========== */}
        <script
          id="openai-pixel"
          dangerouslySetInnerHTML={{
            __html: `!function(w,d,s,u){if(w.oaiq)return;var q=function(){q.q.push(arguments)};q.q=[];w.oaiq=q;var j=d.createElement(s);j.async=1;j.src=u;var f=d.getElementsByTagName(s)[0];f.parentNode.insertBefore(j,f)}(window,document,"script","https://bzrcdn.openai.com/sdk/oaiq.min.js");oaiq("init",{pixelId:"9YggQeUSmz7yJiNTG2JR8q",debug:true});`,
          }}
        />

        {/* ========== CSS — BUNDLED ==========
            All 17 local stylesheets (bootstrap.min, plugin.min, all.min,
            ionicon.min, style, responsive, mega-menu, about, blog,
            home-mega-menu, navbar-redesign, chat-widget, location-pages,
            navbar-dropdown, services, homepage-fixes, ui-fixes) are
            concatenated in their original cascade order and minified into a
            single file by scripts/_css_bundle.py. This drops 16 render-blocking
            requests to 1. Re-run that script after editing any source CSS, then
            bump the ?v= cache-buster below. ========== */}
        <link href="/css/bundle.css?v=20260831a" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Lora:wght@400;500;600;700&family=Sora:wght@600;700;800&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        />

        <meta name="turnstile-site-key" content={process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY} />

        {/* ========== CSS — Third Party ========== */}
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
        />

        {/* Component CSS that used to be injected inline via
            <style dangerouslySetInnerHTML> in ~20 components (~32 KB of every
            HTML response). Extracted to a cacheable file by hand; MUST stay the
            last stylesheet so these rules keep the precedence they had as
            body-level <style> tags. Bump ?v= when editing it. */}
        <link href="/css/component-styles.css?v=8" rel="stylesheet" />

        {/* Footer surface — dark navy + diamond lattice, pinned explicitly.
            style.css declares `.ft-main` twice and BOTH are a light lavender
            gradient, so the dark footer was only winning by bundle order.
            This sheet loads last so a re-run of scripts/_css_bundle.py can
            never flip the footer back to light with dark-on-dark text.
            See public/css/footer-pattern.css for the sampled values. */}
        <link href="/css/footer-pattern.css?v=1" rel="stylesheet" />

        {/* Favicon links are emitted by the `icons` field in the metadata export above */}
      </head>
      <body suppressHydrationWarning>
        {/* ========== GOOGLE TAG MANAGER (noscript) — Global, all pages ========== */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-K2PX82J8"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>
        {/* ========== END GOOGLE TAG MANAGER (noscript) ========== */}

        <Analytics />
        <AOSRefresh />
        <ScrollRestorationManager />
        {/* Makes every internal link open in a new tab, site-wide.
            Skips #hash, mailto/tel, external hosts, /admin and
            anything marked data-same-tab. */}
        <ExternalizeInternalLinks />
        <FaqAccordion />
        {/* Request Quote Modal Overlay (shared) */}
        <QuoteModal />
        {/* Brochure Modal Overlay */}
        <div className="modal-overlay hide" id="brochureModal" role="dialog" aria-modal="true" aria-labelledby="brochureModalTitle">
          <div className="brochure-modal-box">
            <div className="brochure-modal-left">
              <div className="brochure-modal-circle">
                <img width={516} height={546} loading="lazy" decoding="async" src="/images/sliders/mobile_app_development.webp" alt="Web and Mobile App Development" />
              </div>
            </div>
            <div className="brochure-modal-right">
              <button id="closeBrochureModal" className="brochure-close-btn" aria-label="Close brochure modal" type="button">&#10005;</button>
              <h3 id="brochureModalTitle" className="brochure-modal-title">Request Brochure</h3>
              <form id="brochureForm" noValidate>
                <label className="brochure-form-label" htmlFor="brochure_name">Full Name</label>
                <div className="brochure-input-group">
                  <span className="brochure-input-icon">&#128100;</span>
                  <input type="text" id="brochure_name" name="name" placeholder="Full Name" aria-label="Full Name" autoComplete="name" required />
                </div>
                <div className="brochure-error" id="brochure_name_err" aria-live="polite"></div>

                <label className="brochure-form-label" htmlFor="brochure_email">Your Email</label>
                <div className="brochure-input-group">
                  <span className="brochure-input-icon">&#9993;&#65039;</span>
                  <input type="email" id="brochure_email" name="email" placeholder="Email Id" aria-label="Email Address" autoComplete="email" required />
                </div>
                <div className="brochure-error" id="brochure_email_err" aria-live="polite"></div>

                <label className="brochure-form-label" htmlFor="brochure_country">Country Code</label>
                <select id="brochure_country" name="countryCode" className="brochure-form-select" aria-label="Country Code">
                  <option value="+91">India (+91)</option>
                  <option value="+1">USA (+1)</option>
                  <option value="+44">UK (+44)</option>
                  <option value="+61">Australia (+61)</option>
                  <option value="+971">UAE (+971)</option>
                  <option value="+65">Singapore (+65)</option>
                  <option value="+49">Germany (+49)</option>
                  <option value="+33">France (+33)</option>
                  <option value="+81">Japan (+81)</option>
                  <option value="+86">China (+86)</option>
                  <option value="+974">Qatar (+974)</option>
                  <option value="+965">Kuwait (+965)</option>
                  <option value="+966">Saudi Arabia (+966)</option>
                  <option value="+1-ca">Canada (+1)</option>
                </select>

                <label className="brochure-form-label" htmlFor="brochure_phone">Your Mobile</label>
                <div className="brochure-input-group">
                  <span className="brochure-input-icon">&#128241;</span>
                  <input type="tel" id="brochure_phone" name="mobile" placeholder="Contact Number" aria-label="Phone Number" autoComplete="tel" inputMode="numeric" pattern="[0-9]*" maxLength={10} required />
                </div>
                <div className="brochure-error" id="brochure_phone_err" aria-live="polite"></div>

                <div className="cf-turnstile" data-sitekey={process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY} data-callback="onBrochureTurnstileSuccess" suppressHydrationWarning></div>

                <button type="submit" id="brochureSubmitBtn" className="brochure-submit-btn">Submit Now</button>
                <div className="brochure-error brochure-error--form" id="brochure_form_err" aria-live="polite"></div>
              </form>
            </div>
          </div>
        </div>
        <Header />
        <div className="header-spacer"></div>
        {children}
        <Footer />
        {process.env.NEXT_PUBLIC_SHOW_CHATBOT === "true" && <ChatWidget />}
        {/* Floating WhatsApp Button — green circle with white phone
            glyph rendered via CSS mask + two animated pulsing rings
            (see .whatsapp-hero-btn rules in public/css/ui-fixes.css). */}
        <a
          href="https://wa.me/message/H5VADFWLMPYIM1"
          target="_blank"
          rel="noopener noreferrer"
          className="whatsapp-hero-btn"
          aria-label="Chat on WhatsApp"
        >
          {/* Hidden — kept for alt-text / SEO. CSS hides this element. */}
          <img width={34} height={34} loading="lazy" decoding="async"
            src="/images/new_home/ai-product-pages/cybersecurity/whatsapp.webp"
            alt="WhatsApp"
            className="whatsapp-hero-img"
          />
          {/* Foreground white phone glyph (CSS-masked SVG). */}
          <span className="whatsapp-glyph" aria-hidden="true" />
          <span className="wa-tooltip">Chat with us!</span>
        </a>

        {/* ========== JS — Core Libraries ========== */}
        <Script src="/js/jquery-3.6.0.min.js" strategy="afterInteractive" />
        <Script src="/js/bootstrap.bundle.min.js" strategy="afterInteractive" />
        {/* <Script id="app-bundle" strategy="afterInteractive" dangerouslySetInnerHTML={{ __html: `(function c(){if(typeof jQuery!=="undefined"){var s=document.createElement("script");s.src="/js/app.bundle.js";s.onload=function(){var n=document.createElement("script");n.src="/js/navbar-init.js";document.body.appendChild(n)};document.body.appendChild(s)}else{setTimeout(c,100)}})()` }} /> */}
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" strategy="afterInteractive" />
        <Script src="https://unpkg.com/aos@2.3.1/dist/aos.js" strategy="afterInteractive" />

        {/* ========== JS — Site Scripts ========== */}
        {/* <Script id="main-js" strategy="lazyOnload" dangerouslySetInnerHTML={{ __html: `(function c(){if(typeof jQuery!=="undefined"){var s=document.createElement("script");s.src="/js/main.js";document.body.appendChild(s)}else{setTimeout(c,100)}})()` }} /> */}
        
        <Script src="/js/app.bundle.js" strategy="afterInteractive" />
        
<Script src="/js/navbar-init.js" strategy="afterInteractive" />
<Script src="/js/main.js" strategy="afterInteractive" />
        <Script src="/js/mega-menu.js" strategy="lazyOnload" />

        <Script src="/js/site-interactions.js" strategy="lazyOnload" />
        <Script src="/js/faq.js" strategy="afterInteractive" />
        <Script src="/js/tabs.js" strategy="lazyOnload" />
        <Script src="/js/services.js" strategy="lazyOnload" />

 {/* <script src="/js/nav-active.js"></script> */}

        {/* ========== JS — Request Quote Handler ========== */}
        <Script src="/js/request-quote-handler.js" strategy="afterInteractive" />

        {/* ========== JS — Brochure Form Handler (country-aware validation, modal-only) ========== */}
       <Script src="/js/brochure-form-handler.js" strategy="afterInteractive" />

        {/* ========== JS — Bottom Nav Icons ========== */}
        <Script src="/js/bottom-nav-icons.js" strategy="lazyOnload" />

        <Script src="/js/tawk-loader.js" strategy="lazyOnload" />


      </body>
    </html>
  );
}